# Generated by Django 5.2.1 on 2025-05-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_apellidomaterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
