# Generated by Django 5.2.1 on 2025-05-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_permiso_activo_rol_activo'),
        ('usuarios', '0006_remove_usuario_rol_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.rol'),
        ),
    ]
