# Generated by Django 5.2.1 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='rol',
        ),
        migrations.AddField(
            model_name='permiso',
            name='roles',
            field=models.ManyToManyField(related_name='permisos', to='roles.rol'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
