# Generated by Django 5.2.1 on 2025-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_remove_permiso_rol_permiso_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
